config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items do
     resources :comments, only: [:create, :destroy]
     resources :reviews, only: [:create, :destroy]
   end

   root to: 'items#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :item
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :item

  validates :item, presence: true
  validates :user_name, presence: { message: "名前を入力してください" }
  validates :content, presence: { message: "コメントを入力してください" }, length: { in: 1..1000 }
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, presence: { message: "商品名を入力してください" }
  validates :price,
    presence: { message: "価格を入力してください" },
    numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  mount_uploader :picture, ImageUploader
  belongs_to :category
  
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :item

  validates :item, presence: true
  validates :review, presence: { message: "コメントを入力してください！" }
  validates :star,
  presence: { message: "評価を入力してください！" },
  numericality: {
    less_than: 11,
    only_integer: true,
    greater_than_or_equal_to: 0, # 数値であり、0以上11以下の場合有効
    message: '0~10の整数値で入力してください！'
  }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
     @item = Item.find(params[:item_id])
     @comment = Comment.new(params_comment)
     @comment.item = @item

     if @comment.save
       redirect_to item_url(@item)
     else
       render "items/show"
     end
   end

   def destroy
    @item = Item.find(params[:item_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to item_url(@item)
   end

   private

   def params_comment
     params.require(:comment).permit(:user_name, :content)
   end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :destroy]

  def index
    @items = Item.all
    @search = Item.search(params[:q])
    @items = @search.result
  end

  def show
    @item = Item.includes(:comments).find(params[:id])
    @comment = Comment.new
    @item = Item.includes(:reviews).find(params[:id])
    @review = Review.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(params_item)
    if @item.save
       redirect_to item_url(@item)
     else
       render "new"
     end
  end

  def edit
  end

  def update
    if @item.update_attributes(params_item)
      redirect_to item_url(@item)
    else
      render "edit"
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url
  end

  def search
    t = Item.arel_table
    name = params[:name]
    @items = Item.all
    @items = @items.where(t[:name].matches("%#{name}%")) if name.present?
  end

  private

  def params_item
    params.require(:item).permit(:name, :price, :picture, :category, :release)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
     @item = Item.find(params[:item_id])
     @review = Review.new(params_review)
     @review.item = @item

     if @review.save
       redirect_to item_url(@item)
     else
       render "items/show"
     end
   end

   def destroy
    @item = Item.find(params[:item_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to item_url(@item)
   end

   private

   def params_review
     params.require(:review).permit(:review, :star)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_add_fields(name, f, type)
    new_object = f.object.send "build_#{type}"
    id = "new_#{type}"
    fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
      render(type.to_s + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/items/_comment_form.html.erb
<%= form_for @comment, url: item_comments_path(@item, @comment) do |f| %>
  名前: <%= f.text_field :user_name, placeholder: "必須", value: "名無しさん" %><br>
  <% if @comment.errors.any? %>
    <p class="error_message">
      <%= @comment.errors.messages[:user_name][0] %>
    </p>
  <% end %>
  コメント: <%= f.text_area :content,placeholder: "必須", value: "いいね！" %> <br>
  <% if @comment.errors.any? %>
    <p class="error_message">
      <%= @comment.errors.messages[:content][0] %>
    </p>
  <% end %>
  <%= f.submit "コメントする" %>
<% end %>

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <div>
    <div class="form_label">
      商品名:
    </div>
    <!-- .form_label -->
    <div class="form_input">
      <%= f.text_field :name %>
      <% if @item.errors.any? %>
        <p class="error_message">
          <%= @item.errors.messages[:name][0] %>
        </p>
      <% end %>
    </div>
    <!-- .form_input -->
  </div>
  <div>
    <div class="form_label">
      価格:
    </div>
    <!-- .form_label -->
    <div class="form_input">
      <%= f.number_field :price, placeholder: "税込み価格", step: "1" %>
      <% if @item.errors.any? %>
        <p class="error_message">
          <%= @item.errors.messages[:price][0] %>
        </p>
      <% end %>
    </div>
    <!-- .form_input -->
  </div>
  <div>
    <div class="form_label">
      画像:
    </div>
    <!-- .form_label -->
    <div class="form_input">
      <%= f.file_field :picture,accept: "image/jpeg" %>
    </div>
    <!-- .form_input -->
  </div>
  <div>
    <div class="form_label">
      発売日:
    </div>
    <!-- .form_label -->
    <div class="form_input">
      <%=  f.date_select(
        :release,
        use_month_numbers: true,
        start_year:     1930,
        end_year:       (Time.now.year),
        default:        Date.new(1989, 1, 1),
        date_separator: '/') %>
    </div>
    <!-- .form_input -->
  </div>
  <%= f.submit "商品登録" %>
<% end %>

app/views/items/_review_form.html.erb
<% if user_signed_in? then %>
  <%= form_for @review, url: item_reviews_path(@item, @review) do |f| %>
  一言レビュー: <%= f.text_field :review, placeholder: "必須", value: "Sample" %> <br>
  <% if @review.errors.any? %>
    <p class="error_message">
      <%= @review.errors.messages[:review][0] %>
    </p>
  <% end %>
  星の数: <%= f.number_field :star, placeholder: "1~10", value: "5" %> <br>
  <% if @review.errors.any? %>
    <p class="error_message">
      <%= @review.errors.messages[:star][0] %>
    </p>
  <% end %>
  <%= f.submit "レビューする" %>←押してみよう！
  <% end %>
  <% else %>
  <p>
    レビュー機能はログインしたら使えるよ☆
  </p>
<% end %>

app/views/items/edit.html.erb
<div class="wrapper wrapper_bg">
  <div class="container">
    <%= link_to "戻る", item_path(@item) %>
    <hr>
    <h1>新規編集</h1>
    <div class="panel form">
      <%= render 'form' %>
    </div>
    <!-- .panel .form -->
  </div>
  <!-- .container -->
</div>
<!-- .wrapper .wrapper_bg -->

app/views/items/index.html.erb
<div class="wrapper wrapper_bg">
  <div class="container">

    <% if user_signed_in? %>
    <div class="new_item">
      <%= link_to "商品新規登録", new_item_path %>
    </div>
    <!-- new_item -->
    <% end %>

    <div class="search_form">
      <%= search_form_for @search do |f| %>
      <div class="field">
        <%= f.label :name_cont, "Name"%>
        <%= f.text_field :name_cont, placeholder: "name contains" %>
      </div>
      <!-- .field -->
      <div class="field">
        <%= f.label :price_gteq, "Between" %>
        <%= f.text_field :price_gteq, placeholder: "price" %>
        <%= f.label :price_lteq, "~" %>
        <%= f.text_field :price_lteq, placeholder: "price" %>
        <%= f.submit "Search" %>
      </div>
      <!-- .field -->
    <% end %>
    </div>
    <!-- .search_form -->

    <hr>
    <div class="panel">
      <table class="table">
        <thead>
          <tr>
            <th>
            </th>
            <th>
              <p>
              <%= sort_link(@search, :name, "Name") %>
              </p>
            </th>
            <th>
              <p>
              <%= sort_link(@search, :price, "Price") %>
              </p>
            </th>
            <th>
              <p>
              <%= sort_link(@search, :release, "ReleaseDay") %>
              </p>
            </th>
            <th>
              <p>
              <%= sort_link(@search, :cleate, "CreateDay") %>
              </p>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td>
              <div class="thumbnail">
                <%= image_tag item.picture.url %>
              </div>
            </td>
            <td>
            <%= link_to item.name, item_path(item) %>
            </td>
            <td>
            <%= item.price %>
            </td>
            <td>
            <%= item.release %>
            </td>
            <td>
            <%= item.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <!-- .panel -->
  </div>
  <!-- .container -->
</div>
<!-- .wrapper .wrapper_bg -->

app/views/items/new.html.erb
<div class="wrapper wrapper_bg">
  <div class="container">
    <div class="back">
      <%= link_to "戻る", items_path %>
    </div>
    <hr>
    <div class="panel form">
      <h1>新規登録</h1>
      <%= render 'form' %>
    </div>
    <!-- .panel .form -->
  </div>
  <!-- .container -->
</div>
<!-- .wrapper .wrapper_bg -->

app/views/items/show.html.erb
<div class="wrapper wrapper_bg">
  <div class="container">
    <div class="back">
      <%= link_to "戻る", items_path %>
    </div>
    <hr>
    <div class="item">
      <h1 class="item-name"><%= @item.name %></h1>
      <h1 class="item-image"><%= image_tag @item.picture.url %></h1>
      <h2 class="item-price"><%= @item.price %>円</h2>
      <h2 class="item-release">発売日：<%= @item.release %></h2>
    </div>
    <!-- .item -->
    <div class="edit_del">
    <% if user_signed_in? %>
      <%= link_to "編集", edit_item_path(@item) %>
      <%= link_to "削除", item_path(@item), method: :delete, data: { confirm: "本当に削除しますか？" } %>
    <% end %>
    </div>
    <hr>
    <div class="review">
      <% @item.reviews.each_with_index do |review, index| %>
      <div class="review_box">
        <div class="review_head">
          <%= index + 1 %>：
          <%= review.created_at.strftime("%Y/%m/%d %H:%M:%S ") %>：レビュー評価
        </div>
        <!-- .review_head-->
        <div class="review_body">
          一言「<%= review.review %>」:
          <%= review.star %>
        </div>
        <!-- review_body -->
      </div>
      <!-- .review_box -->
      <% end %>
    </div>
    <!-- .review -->

    <hr>
    <div class="comment">
      <% @item.comments.each_with_index do |comment, index| %>
        <div class="comment_box">
          <div class="comment_head">
            <%= index + 1 %>：
            <%= comment.user_name %>
            <%= comment.created_at.strftime("%Y/%m/%d %H:%M:%S ") %>
          </div>
          <!-- .comment_head -->
          <div class="comment_body">
            <%= comment.content %>
          </div>
          <!-- .comment_body -->
        </div>
        <!-- .comment_box -->
      <% end %>
    </div>
    <!-- .comment -->
    <hr>
    <div class="review_form">
      <%= render 'review_form' %>
    </div>
    <hr>
    <div class="comment_form">
      <%= render 'comment_form' %>
    </div>
  </div>
  <!-- .container -->
 </div>
<!-- .wrapper .wrapper_bg -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReviewApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
    <p>
      <%= link_to image_tag("logo.jpg"), items_path %>
    </p>
  <nav>
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.<br>
      <%= link_to 'プロフィール変更', edit_user_registration_path %> |
      <%= link_to "ログアウト", destroy_user_session_path, method: :get %>
    <% else %>
      <%= link_to "サインイン", new_user_registration_path %> |
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>
  </nav>
</header>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div id="container_left">
  <a href="https://px.a8.net/svt/ejp?a8mat=2TAHNF+4W8BUA+FOQ+CCQSX" target="_blank">
  <img border="0" width="120" height="600" alt="" src="https://www25.a8.net/svt/bgt?aid=170130651296&wid=001&eno=01&mid=s00000002033002075000&mc=1"></a>
  <img border="0" width="1" height="1" src="https://www18.a8.net/0.gif?a8mat=2TAHNF+4W8BUA+FOQ+CCQSX" alt="">
</div>
<div id="container_right">
  <div class="container_panel">
    <a href="https://rpx.a8.net/svt/ejp?a8mat=2TAHNF+4V1GMQ+2HOM+5ZMCH&rakuten=y&a8ejpredirect=http%3A%2F%2Fhb.afl.rakuten.co.jp%2Fhgc%2F0ea62065.34400275.0ea62066.204f04c0%2Fa17013074213_2TAHNF_4V1GMQ_2HOM_5ZMCH%3Fpc%3Dhttp%253A%252F%252Fwww.rakuten.co.jp%252F%26m%3Dhttp%253A%252F%252Fm.rakuten.co.jp%252F" target="_blank">
    <img src="http://hbb.afl.rakuten.co.jp/hsb/0eb4bbb0.174cb205.0eb4bbaa.95151395/" border="0"></a>
    <img border="0" width="1" height="1" src="https://www15.a8.net/0.gif?a8mat=2TAHNF+4V1GMQ+2HOM+5ZMCH" alt="">
    <br>
    <a href="https://rpx.a8.net/svt/ejp?a8mat=2TAHNF+4V1GMQ+2HOM+6S4KX&rakuten=y&a8ejpredirect=http%3A%2F%2Fhb.afl.rakuten.co.jp%2Fhgc%2F0eac8dc2.9a477d4e.0eac8dc3.0aa56a48%2Fa17013074213_2TAHNF_4V1GMQ_2HOM_6S4KX%3Fpc%3Dhttp%253A%252F%252Fbooks.rakuten.co.jp%252F%26m%3Dhttp%253A%252F%252Fbooks.rakuten.co.jp%252F" target="_blank">
    <img src="http://hbb.afl.rakuten.co.jp/hsb/0eb46e3c.be43ce35.0eb46e39.39a610d9/" border="0"></a>
    <img border="0" width="1" height="1" src="https://www16.a8.net/0.gif?a8mat=2TAHNF+4V1GMQ+2HOM+6S4KX" alt="">
    <br>
    <a href="https://px.a8.net/svt/ejp?a8mat=2TAHNF+4WTRG2+37HI+5ZEMP" target="_blank">
    <img border="0" width="120" height="60" alt="" src="https://www25.a8.net/svt/bgt?aid=170130651297&wid=001&eno=01&mid=s00000014967001005000&mc=1"></a>
    <img border="0" width="1" height="1" src="https://www13.a8.net/0.gif?a8mat=2TAHNF+4WTRG2+37HI+5ZEMP" alt="">
    <br>
    <a href="https://px.a8.net/svt/ejp?a8mat=2TAHNF+4VMW8I+CW6+C8NROH" target="_blank">
    <img border="0" width="120" height="60" alt="" src="https://www26.a8.net/svt/bgt?aid=170130651295&wid=001&eno=01&mid=s00000001671074014000&mc=1"></a>
    <img border="0" width="1" height="1" src="https://www19.a8.net/0.gif?a8mat=2TAHNF+4VMW8I+CW6+C8NROH" alt="">
  </div>
</div>
<div id="container">
  <%= yield %>
</div>
<footer>
  <a href="#top">
    <p>Let's review!</p>
  </a>
</footer>

</body>
</html>